### ISSUE TITLE
It can not install

### ISSUE THREAD

**Issue by panxiaoguang** [cttobin/ggthemr#29] opened 2018-09-19 08:27 UTC
the ggthemr can not be installed in R-3.5.1,can you update it?

**Comment by CamMakoJ** [comment] 2019-02-10 17:45
ill second this

**Comment by sainathadapa** [comment] 2019-02-12 13:32
Can you post more details about the issues that you are facing? I have just tested on a fresh install and did not face any issues.

```> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggthemr_1.1.0 ggplot2_3.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       rstudioapi_0.9.0 bindr_0.1.1      magrittr_1.5     tidyselect_0.2.5
 [6] munsell_0.5.0    colorspace_1.4-0 R6_2.3.0         rlang_0.3.1      plyr_1.8.4      
[11] dplyr_0.7.8      tools_3.5.2      grid_3.5.2       gtable_0.2.0     withr_2.1.2     
[16] digest_0.6.18    yaml_2.2.0       lazyeval_0.2.1   assertthat_0.2.0 tibble_2.0.1    
[21] crayon_1.3.4     bindrcpp_0.2.2   purrr_0.3.0      glue_1.3.0       labeling_0.3    
[26] compiler_3.5.2   pillar_1.3.1     scales_1.0.0     pkgconfig_2.0.2 ```

**Comment by CamMakoJ** [comment] 2019-02-12 18:24
This is the error i get - > devtools::install_github('cttobin/ggthemr')
Downloading GitHub repo cttobin/ggthemr@master
√  checking for file 'C:\Users\Cam Johnston\AppData\Local\Temp\Rtmpgj403i\remotes21241816d22\cttobin-ggthemr-0a31bb5/DESCRIPTION' ...
-  preparing 'ggthemr':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'ggthemr/README_files'
-  building 'ggthemr_1.1.0.tar.gz'
   
Installing package into ‘C:/Users/Cam Johnston/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'ggthemr' ...
** R
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'ggthemr'
    finding HTML links ... done
    align_title_left                        html  
    align_title_right                       html  
    colour_plot                             html  
    darken_gradient                         html  
    darken_palette                          html  
    darken_swatch                           html  
    define_palette                          html  
    define_swatch                           html  
    get_themr                               html  
    ggthemr                                 html  
    ggthemr_current                         html  
    ggthemr_reset                           html  
    is_colour                               html  
    is_ggthemr                              html  
    legend_position                         html  
    lighten_gradient                        html  
    lighten_palette                         html  
    lighten_swatch                          html  
    move_legend                             html  
    no_axes                                 html  
    no_axes_titles                          html  
    no_gridlines                            html  
    no_legend                               html  
    no_legend_title                         html  
    no_major_gridlines                      html  
    no_major_x_gridlines                    html  
    no_major_y_gridlines                    html  
    no_minor_gridlines                      html  
    no_minor_x_gridlines                    html  
    no_minor_y_gridlines                    html  
    no_ticks                                html  
    no_title                                html  
    no_x_axis                               html  
    no_x_gridlines                          html  
    no_x_line                               html  
    no_x_text                               html  
    no_x_ticks                              html  
    no_x_title                              html  
    no_y_axis                               html  
    no_y_gridlines                          html  
    no_y_line                               html  
    no_y_text                               html  
    no_y_ticks                              html  
    no_y_title                              html  
    plot.ggthemr                            html  
    plot.ggthemr_palette                    html  
    plot.ggthemr_swatch                     html  
    random_swatch_colour                    html  
    reverse_gradient                        html  
    rotate_axes_text                        html  
    rotate_x_text                           html  
    rotate_y_text                           html  
    set_swatch                              html  
    set_themr                               html  
    shuffle_swatch                          html  
    swatch                                  html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
ARGUMENT 'Johnston\AppData\Local\Temp\RtmpwPZjbo\Rin3b1871a03021' __ignored__

Error: unexpected input in "OSGEO4W_ROOT=C:\"
Execution halted
*** arch - x64
ARGUMENT 'Johnston\AppData\Local\Temp\RtmpwPZjbo\Rin3b183ab46dce' __ignored__

Error: unexpected input in "OSGEO4W_ROOT=C:\"
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Cam Johnston/Documents/R/win-library/3.4/ggthemr'
In R CMD INSTALL
Error: (converted from warning) running command '"C:/R/R-3.4.4/bin/x64/R" CMD INSTALL -l "C:\Users\Cam Johnston\Documents\R\win-library\3.4" "C:/Users/Cam Johnston/AppData/Local/Temp/Rtmpgj403i/file212477e15ccd/ggthemr_1.1.0.tar.gz"' had status 1

**Comment by sainathadapa** [comment] 2019-02-12 18:36
can you post the output of `sessionInfo() `

**Comment by CamMakoJ** [comment] 2019-02-12 18:39
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        ps_1.3.0          prettyunits_1.0.2 rprojroot_1.3-2   withr_2.1.2       digest_0.6.18     crayon_1.3.4      assertthat_0.2.0 
 [9] R6_2.3.0          backports_1.1.3   magrittr_1.5      rlang_0.3.1       cli_1.0.1         curl_3.3          fs_1.2.6          remotes_2.0.2    
[17] rstudioapi_0.9.0  callr_3.1.1       desc_1.2.0        devtools_2.0.1    tools_3.4.4       glue_1.3.0        pkgload_1.0.2     compiler_3.4.4   
[25] processx_3.2.1    pkgbuild_1.0.2    sessioninfo_1.1.1 memoise_1.1.0     usethis_1.4.0

**Comment by sainathadapa** [comment] 2019-02-13 11:22
https://community.rstudio.com/t/package-socviz-does-not-load-in-r-microsoft-open-3-5-1/23498
It seems like the issue is that your username has spaces in it. Can you check with a username that has no spaces in it? I wonder why you haven't faced this issue with other packages.

**Comment by sainathadapa** [comment] 2019-02-13 11:27
https://community.rstudio.com/t/spaces-in-library-path-names-on-windows-causes-problems-installing-packages-after-installing-r-3-5-0/8978/5

**Comment by sainathadapa** [comment] 2019-02-18 06:28
I'm closing the issue for now. Feel free to re-open/comment if you feel the issue isn't resolved by changing your username.

**Closed by sainathadapa** 2019-02-18 06:28 UTC
